feat(core):  add helper function to get the field by key
ngx-formly/ngx-formly pull request #2864
Opened 2021-05-26 01:35 UTC by nirmpate

add get method to field type

Closes #2854

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
https://github.com/ngx-formly/ngx-formly/issues/2854

**What is the new behavior (if this is a feature change)?**

field components will be able to get child field if there is a fieldGroup present. 

**Please check if the PR fulfills these requirements**
- [ x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x ] A unit test has been written for this change.
- [ x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [ x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

2021-08-16 14:02 UTC, MaxKless commented
@nirmpate what do you think of enabling recursive searching with an array of rest parameters instead of just searching for the field key until you find it? This way, the user would have granular control of which nested field they're looking for.

2021-08-19 20:42 UTC, aitboudad requested changes

2021-08-19 20:42 UTC, aitboudad commented on src/core/src/lib/extensions/core/core.ts
> +        const findField = (f: FormlyFieldConfig, keyValue: string | number) => {
move this to [util](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/utils.ts) file.

2021-08-19 20:42 UTC, aitboudad commented on src/core/src/lib/extensions/core/core.ts
> +            const match = f.fieldGroup.find((fg) => fg.key && fg.key === keyValue);
we need to manage two extra cases:
- nested key `address.city`.
- finding field by `id` which is useful for a field that doesn't have a key

2021-08-21 23:28 UTC, nirmpate commented
> @nirmpate what do you think of enabling recursive searching with an array of rest parameters instead of just searching for the field key until you find it? This way, the user would have granular control of which nested field they're looking for.

This is an interesting idea.  I'm not exactly sure if I understand it though.  So if the get function can take multiple arguments such as field.get(...args).  This array of args would target a specific path to the field you're searching for?

2021-08-24 12:36 UTC, MaxKless commented
> This is an interesting idea. I'm not exactly sure if I understand it though. So if the get function can take multiple arguments such as field.get(...args). This array of args would target a specific path to the field you're searching for?

Yes exactly. Check out the [relevant typescript docs](https://www.typescriptlang.org/docs/handbook/2/functions.html#rest-parameters-and-arguments). I imagine you could just iterate over the array recursively and find the nested keys.

2021-11-04 14:20 UTC, closed without merging

2021-11-04 14:21 UTC, aitboudad commented
close in favor #3040