Fix: Performance decline issue
ngx-formly/ngx-formly pull request #3994
Opened 2024-09-26 17:39 UTC by sesidhar01

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix

**What is the current behavior? (You can also link to an open issue here)**

https://github.com/ngx-formly/ngx-formly/issues/3984

**What is the new behavior (if this is a feature change)?**

**Please check if the PR fulfills these requirements**
- [ ] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] A unit test has been written for this change.
- [ ] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [ ] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

2024-10-07 06:45 UTC, aitboudad requested changes

2024-10-07 06:45 UTC, aitboudad commented on src/core/src/lib/components/formly.field.ts
> +    const propsObserver = observe(field, ['props'], () => field.options.detectChanges(field));
I think we should keep `observeDeep`. if there is a specific case where the perf drop we need to provide a fix for. `observeDeep` instead.

2024-10-07 06:45 UTC, aitboudad commented on src/core/src/lib/components/formly.form.ts
> +            fieldChangesDetection.push(() => observe(this.field.options, ['formState'], () => this.field.options.detectChanges(this.field)));
use `observeDeep`

2024-10-07 21:02 UTC, aitboudad approved these changes

2024-10-07 21:03 UTC, merged

2024-10-07 21:04 UTC, aitboudad commented
Thank you @sesidhar01!

2024-10-07 21:13 UTC, kenisteward commented
@sesidhar01  thanks buddy!  We'll get this into our wrapper lib ASAP

2024-10-08 01:18 UTC, sesidhar01 commented
> Thank you @sesidhar01!

@aitboudad Thanks for merging any idea when this change can be published?

2024-10-08 06:28 UTC, aitboudad commented
> Thanks for merging any idea when this change can be published?

I'll try to make a new release at the end of this week.